#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC94D18F7F05997E (jr@jriddell.org)
#
Name     : bluedevil
Version  : 5.13.4
Release  : 1
URL      : https://download.kde.org/stable/plasma/5.13.4/bluedevil-5.13.4.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.13.4/bluedevil-5.13.4.tar.xz
Source99 : https://download.kde.org/stable/plasma/5.13.4/bluedevil-5.13.4.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: bluedevil-bin
Requires: bluedevil-lib
Requires: bluedevil-data
Requires: bluedevil-locales
BuildRequires : bluez-qt-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kded-dev
BuildRequires : plasma-framework-dev
BuildRequires : shared-mime-info

%description
BlueDevil runtime dependencies:
-bluez5
-General Bluetooth management
-bluez-obexd
-Be able to "Browse File" aka kio_obexftp
-Be able to "Send Files" (bluedevil-sendfile)
-Be able to receive files

%package bin
Summary: bin components for the bluedevil package.
Group: Binaries
Requires: bluedevil-data

%description bin
bin components for the bluedevil package.


%package data
Summary: data components for the bluedevil package.
Group: Data

%description data
data components for the bluedevil package.


%package lib
Summary: lib components for the bluedevil package.
Group: Libraries
Requires: bluedevil-data

%description lib
lib components for the bluedevil package.


%package locales
Summary: locales components for the bluedevil package.
Group: Default

%description locales
locales components for the bluedevil package.


%prep
%setup -q -n bluedevil-5.13.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535209306
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535209306
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
%find_lang bluedevil
%find_lang plasma_applet_org.kde.plasma.bluetooth

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bluedevil-sendfile
/usr/bin/bluedevil-wizard

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.bluedevilsendfile.desktop
/usr/share/applications/org.kde.bluedevilwizard.desktop
/usr/share/bluedevilwizard/pin-code-database.xml
/usr/share/knotifications5/bluedevil.notifyrc
/usr/share/kservices5/bluedeviladapters.desktop
/usr/share/kservices5/bluedevildevices.desktop
/usr/share/kservices5/bluedevilfileitemaction.desktop
/usr/share/kservices5/bluedevilglobal.desktop
/usr/share/kservices5/bluetooth.protocol
/usr/share/kservices5/obexftp.protocol
/usr/share/kservices5/plasma-applet-org.kde.plasma.bluetooth.desktop
/usr/share/metainfo/org.kde.plasma.bluetooth.appdata.xml
/usr/share/mime/packages/bluedevil-mime.xml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/BluetoothApplet.qml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/CompactRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/DeviceItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/Header.qml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/MediaPlayerItem.qml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/SwitchButton.qml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/Toolbar.qml
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/logic.js
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.plasma.bluetooth/metadata.json
/usr/share/remoteview/bluetooth-network.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/bluetoothfileitemaction.so
/usr/lib64/qt5/plugins/kcm_bluedeviladapters.so
/usr/lib64/qt5/plugins/kcm_bluedevildevices.so
/usr/lib64/qt5/plugins/kcm_bluedevilglobal.so
/usr/lib64/qt5/plugins/kf5/kded/bluedevil.so
/usr/lib64/qt5/plugins/kio_bluetooth.so
/usr/lib64/qt5/plugins/kio_obexftp.so
/usr/lib64/qt5/qml/org/kde/plasma/private/bluetooth/libbluetoothplugin.so
/usr/lib64/qt5/qml/org/kde/plasma/private/bluetooth/qmldir

%files locales -f bluedevil.lang -f plasma_applet_org.kde.plasma.bluetooth.lang
%defattr(-,root,root,-)

